const A = 5;
const B = 5;

const igual = A == B;// Igual a...
const estritamenteIgual = A === B // valores estritamentes iguais 
const diferentes = A != B // Valores di....
const estritamenteDiferente = A !== B // ...
const maiorQUE = A > B // ...
const menorQUE = A < B // ....
const maiorOuIgual = A >= B //...
const menorOuIgual = A <= B // ....

console.log(igual)
console.log(estritamenteIgual)


