// EXE4

// trazer os seguintes dados de 6 usuarios 

// NOME 
// SOBRENOME
// CIDADE 
// CPF 
// NOME DA AGENCIA DE BANCO EX: NUBANK, SANTANDER...
// SALARIO 
// FAZER A SOMA DOS SALDOS SALARIAIS 
// DEPOIS FAZER A DIVISAO POR 6
// E FAZER UMA IF E ELSE COM O VALOR DIVIDIDO DOS SALARIOS..
// SE A PESSSOA É MILHONARIA, RICA, BEM DE VIDA, CLASSE MEDIA E POBRE 

// DEPOIS FAZER UMA SAUDACAO 
// EX:  seu nome é lucas... sua idade.. seu cpf.. sua conta... 

