// EXE7

// trazer os seguintes dados de 5 usuarios 

// NOME 
// SOBRENOME
// CIDADE 
// CPF 
// NOME DA AGENCIA DE BANCO EX: NUBANK, SANTANDER...
// SALARIO 
// FAZER A SOMA DOS SALDOS SALARIAIS 
// DEPOIS FAZER A DIVISAO POR 6
// E FAZER UMA IF E ELSE 
// SE A PESSSOA É MILHONARIA, RICA, BEM DE VIDA, CLASSE MEDIA E POBRE 
// E ULTILIZAR O FOR PARA FICAR MAIS FACIL DE CODAR ESSA ATIVIDADE 
// E FAZER UMA ARRAY


// DEPOIS FAZER UMA SAUDACAO 
// EX:  seu nome é lucas... sua idade.. seu cpf.. sua conta... 

